### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by kaansancak** [qitianwu/SGFormer#10]
Hi,

Thanks for open sourcing your implementation. I am trying to run your examples as pointed in the run.sh file, but it seems like it is throwing error.

```
Traceback (most recent call last):
  File "/localscratch/SGFormer/large/main-batch.py", line 143, in <module>
    out_i = model(x_i, edge_index_i)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/localscratch/SGFormer/large/ours.py", line 268, in forward
    x2 = self.graph_conv(x, edge_index)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/localscratch/SGFormer/large/ours.py", line 86, in forward
    x = conv(x, edge_index, layer_[0])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/localscratch/SGFormer/large/ours.py", line 33, in forward
    adj = SparseTensor(row=col, col=row, value=value, sparse_sizes=(N, N))
  File "/usr/local/lib/python3.10/dist-packages/torch_sparse/tensor.py", line 26, in __init__
    self.storage = SparseStorage(
  File "/usr/local/lib/python3.10/dist-packages/torch_sparse/storage.py", line 69, in __init__
    assert trust_data or int(row.max()) < M
RuntimeError: CUDA error: an illegal memory access was encountered
```

This usually happens because of incorrect SparseTensor construction, i.e. it waits for rows/columns to be sorted.

The error occurred with this command

```
python main-batch.py --method sgformer  --dataset ogbn-proteins --metric rocauc --lr 0.01 --hidden_channels 64     --gnn_num_layers 2  --gnn_dropout 0. --gnn_weight_decay 0. --gnn_use_residual --gnn_use_weight --gnn_use_bn --gnn_use_act     --trans_num_layers 1 --trans_dropout 0. --trans_weight_decay 0. --trans_use_residual --trans_use_weight --trans_use_bn     --use_graph --graph_weight 0.5     --batch_size 10000 --seed 123 --runs 5 --epochs 1000 --eval_step 9 --device 1
```

Can you also clarify why the sparse adj needs to be reconstructed for every layer per forward pass?

```
    def forward(self, x, edge_index, x0):
        N = x.shape[0]
        row, col = edge_index
        d = degree(col, N).float()
        d_norm_in = (1. / d[col]).sqrt()
        d_norm_out = (1. / d[row]).sqrt()
        value = torch.ones_like(row) * d_norm_in * d_norm_out
        value = torch.nan_to_num(value, nan=0.0, posinf=0.0, neginf=0.0)
        adj = SparseTensor(row=col, col=row, value=value, sparse_sizes=(N, N))
        x = matmul(adj, x)  # [N, D]

        if self.use_init:
            x = torch.cat([x, x0], 1)
            x = self.W(x)
        elif self.use_weight:
            x = self.W(x)

        return x
```

Why can't you just cache the normalized adj matrix and reuse it?

For amazon2m, I am getting a similar error:
```
Traceback (most recent call last):
  File "/localscratch/SGFormer/large/main-batch.py", line 143, in <module>
    out_i = model(x_i, edge_index_i)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/localscratch/SGFormer/large/ours.py", line 268, in forward
    x2 = self.graph_conv(x, edge_index)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/localscratch/SGFormer/large/ours.py", line 86, in forward
    x = conv(x, edge_index, layer_[0])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/localscratch/SGFormer/large/ours.py", line 37, in forward
    x = torch.cat([x, x0], 1)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by qitianwu** [comment]
Hi Kaan,

The codes run smoothly on my side. For the error you encountered, are you using the consistent package/environment as described in the Readme?

For the graph adjacency, one can pre-compute and cache it for re-using at each layer. But it may not bring up considerable efficiency improvement, because for the large-sized graph, we use mini-batch training where the input nodes within one mini-batch are randomly sampled and the graph adjacency needs construction for each mini-batch. Also, we only use shallow GNN layers (e.g., 1-3) in practice, which works pretty well and efficiently.

**Comment by kaansancak** [comment]
I don't think the readme contains any instructions on the packages but I just realized there is requirements file within each subfolder. It seems like the code does not work with pytorch 2.x, but works with 1.9+. My confusion is that the SparseTensor construction is throwing the runtime error -- there might be some extra assertions added in new torch_sparse.

For the minibatch, I am aware the need to construct edge indices for minibatches,  this way for each forward pass the adj needs to be recomputed. I agree that correctness-wise they should be same, but operation itself might slow down the training due to overheads such as additional additional sync. needs.

Thanks for the quick response!
